### ISSUE TITLE
Consolidate with firebase-arduino

### ISSUE THREAD

**Issue by proppy** [ioxhop/IOXhop_FirebaseESP32#1]
@maxpromer Thanks for working on this!

Do you have plans to contribute the ESP32 port to https://github.com/firebase/firebase-arduino ?

It'd be nice to consolidate the two libraries into one.

**Comment by maxpromer** [comment]
@proppy I did not know about edit firebase-arduino to work on ESP32 so i make new libraries.

**Comment by pikolo84** [comment]
Great contribution.
