### ISSUE TITLE
tag level

### ISSUE THREAD

**Issue by angelvil** [ioxhop/IOXhop_FirebaseESP32#4]
Hi, your code works fine! but i have a question... How to can Set/Get value of one tag of second level in arduino code? For example:

I would like to create a tag inside of User:

User:
      Name:
      Telf:

Thanks!!

**Comment by maxpromer** [comment]
you can send type JsonObject or JsonArray to `.set` `.push`

this example
```c++
StaticJsonBuffer<200> jsonBuffer;
JsonObject& root = jsonBuffer.createObject();
root["User"] = "angelvil";
root["Name"] = "angelvil";
root["Telf"] = ":-)";
Firebase.push("/users", root);
```

see more https://arduinojson.org/v5/example/
