### ISSUE TITLE
Fonction GET vs STream

### ISSUE THREAD

**Issue by MaxESP** [ioxhop/IOXhop_FirebaseESP32#5]
Really good job it' was the unique firebase version with work with my esp32

I don't understand one  thing why the get function id really very slower than stream fonction

10 second for get function
1  second for  stream fonction to get the array 

if you have an idear

**Comment by maxpromer** [comment]
because `GET` connect and disconnect to firebase every use but `Stream` connect and not disconnect so `Stream` fast more than `GET`

**Comment by MaxESP** [comment]
Thank you very much for your reply i am facing a problem

I wan to exract from stream  String data = stream.getDataString();

[null,{"heures":14,"minutes":11,"scenarioID":1},{"heures":15,"minutes":5,"scenarioID":2}]

14 hour 11 minutes from id1 and 15h 5mn from ID2.

The purpuse is to compare time Int event from firebase to Int time system of esp32 ntp time

**Comment by maxpromer** [comment]
You can use JsonObject

this example

```c++
JsonObject obj = stream.getData();
Serial.println(obj["heures"]);
Serial.println(obj["scenarioID"]);
```

... in firebase don't have array. any array replace by object (if use `.push` key of object will auto gen)

**Comment by MaxESP** [comment]
here is the error 

 Firebase.stream("/Alarme/1", [](FirebaseStream stream) {
// String eventType = stream.getEvent();
    JsonObject obj = stream.getData();
//    String eventType = stream.getEvent();
//    String data = stream.getDataString();
//   Serial.println(stream.getDataString());
Serial.println(obj["heures"]);
    });


![exp firebase](https://user-images.githubusercontent.com/41333143/54265967-b9f7e800-4576-11e9-8099-043984988253.jpg)

**Comment by MaxESP** [comment]
arduino give me json object error

**Comment by MaxESP** [comment]
thank you again for your help i have got those value by json 

how can i stop the stream until a new event

**Comment by maxpromer** [comment]
use `Firebase.stopStream()`

**Comment by MaxESP** [comment]
thanks very very a lot for Firebase.stopStream()

for esp32 when i put a static ip it ' not work why?

**Comment by MaxESP** [comment]
Thanks Thaznk A lot i have fix fix ip

**Comment by UmairAhmed85** [comment]
> here is the error
> 
> Firebase.stream("/Alarme/1", [](FirebaseStream stream) {
> // String eventType = stream.getEvent();
> JsonObject obj = stream.getData();
> // String eventType = stream.getEvent();
> // String data = stream.getDataString();
> // Serial.println(stream.getDataString());
> Serial.println(obj["heures"]);
> });
> 
> ![exp firebase](https://user-images.githubusercontent.com/41333143/54265967-b9f7e800-4576-11e9-8099-043984988253.jpg)

@MaxESP how did you solve this JsonObject error, can you please guide. I need the complete object with new changes using this stream method and facing the same issue as you wrote above i.e. no matching function for call to 'ArduinoJson::JsonObject::JsonObject()'

Please guide, it would be highly appreciated.
